# Generated by Django 4.1.2 on 2022-10-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=255)),
                ('agreement', models.IntegerField(verbose_name='Соглашение')),
                ('act_date', models.DateTimeField(verbose_name='Дата акта')),
                ('status', models.CharField(max_length=255, verbose_name='Статус')),
                ('author', models.IntegerField(verbose_name='Автор')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуален?')),
            ],
            options={
                'verbose_name': 'Статус Акта',
                'verbose_name_plural': 'Статусы Актов',
                'db_table': 'act_status',
                'ordering': ('-updated', '-created'),
            },
        ),
        migrations.RenameField(
            model_name='act',
            old_name='state',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='agreement',
            name='address',
            field=models.CharField(max_length=1024, verbose_name='Адрес объекта'),
        ),
        migrations.DeleteModel(
            name='ActStates',
        ),
        migrations.AddField(
            model_name='actstatus',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projecta.act', verbose_name='Акт'),
        ),
    ]
