# Generated by Django 4.1.2 on 2022-10-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0002_actstatus_rename_state_act_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='projecta.client', verbose_name='Клиент'),
        ),
        migrations.AlterUniqueTogether(
            name='act',
            unique_together={('act_number', 'agreement')},
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together={('agreement_number', 'executor')},
        ),
    ]
