# Generated by Django 4.1.2 on 2022-10-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0004_alter_act_created_alter_act_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_date',
            field=models.DateField(verbose_name='Дата акта'),
        ),
        migrations.AlterField(
            model_name='act',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Создан'),
        ),
    ]
