# Generated by Django 4.1.2 on 2022-10-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0005_alter_act_act_date_alter_act_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Номер акта'),
        ),
        migrations.AlterField(
            model_name='actstatus',
            name='act_date',
            field=models.DateField(verbose_name='Дата акта'),
        ),
    ]
