# Generated by Django 4.1.2 on 2022-10-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0006_alter_act_act_number_alter_actstatus_act_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_number',
            field=models.CharField(max_length=255, verbose_name='Номер акта'),
        ),
    ]
