# Generated by Django 4.1.2 on 2022-10-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0007_alter_act_act_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actstatus',
            name='act_date',
        ),
        migrations.RemoveField(
            model_name='actstatus',
            name='act_number',
        ),
        migrations.RemoveField(
            model_name='actstatus',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='agreementstatus',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agreementstatus',
            name='agreement_number',
        ),
        migrations.RemoveField(
            model_name='agreementstatus',
            name='author',
        ),
        migrations.RemoveField(
            model_name='agreementstatus',
            name='client',
        ),
        migrations.RemoveField(
            model_name='agreementstatus',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='agreementstatus',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='agreementstatus',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='author',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='executor',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='index',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='inn',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='kpp',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='legal_address',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='name',
        ),
        migrations.RemoveField(
            model_name='clientstatus',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='ticketstatus',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='ticketstatus',
            name='type',
        ),
        migrations.AddField(
            model_name='agreement',
            name='class_danger',
            field=models.CharField(default='3 класс', max_length=255, verbose_name='Класс опасности'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='date_reg_certificate',
            field=models.DateField(default='2022-11-11', verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agreement',
            name='num_reg_certificate',
            field=models.CharField(default=1, max_length=255, verbose_name='Сертификат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executor',
            name='num_reg_certificate',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Сертификат'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agreement',
            name='status',
            field=models.CharField(choices=[('Б/С', 'Б/С'), ('У клиента', 'У клиента'), ('Подписан', 'Подписан'), ('ЭДО', 'ЭДО'), ('Расторгнут', 'Расторгнут')], default='Б/С', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='agreementstatus',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(default='Б/С', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Статус'),
        ),
    ]
