# Generated by Django 4.1.2 on 2022-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0009_agreementstatus_author_clientstatus_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementstatus',
            name='author',
            field=models.IntegerField(verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='author',
            field=models.IntegerField(verbose_name='Автор'),
        ),
    ]
