# Generated by Django 4.1.2 on 2022-10-26 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0010_alter_agreementstatus_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(max_length=255)),
                ('check_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'check',
                'ordering': ('-updated', '-created'),
            },
        ),
        migrations.AlterField(
            model_name='act',
            name='status',
            field=models.CharField(choices=[('Б/С', 'Б/С'), ('У клиента', 'У клиента'), ('Подписан', 'Подписан'), ('ЭДО', 'ЭДО')], default='Б/С', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='num_reg_certificate',
            field=models.CharField(max_length=255, verbose_name='Регистрационный №'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Б/С', 'Б/С'), ('В работе', 'В работе'), ('Выполнил', 'Выполнил')], default='Б/С', max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='status',
            field=models.CharField(default='Б/С', max_length=255, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CheckStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='projecta.check', verbose_name='Счет')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статус счета',
                'verbose_name_plural': 'Статусы счетов',
                'db_table': 'check_status',
                'ordering': ('-updated', '-created'),
            },
        ),
        migrations.AddField(
            model_name='check',
            name='act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='projecta.act', verbose_name='Акты'),
        ),
        migrations.AddField(
            model_name='check',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
