# Generated by Django 4.1.2 on 2022-10-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0011_check_alter_act_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkstatus',
            name='_check',
            field=models.IntegerField(verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='checkstatus',
            name='author',
            field=models.IntegerField(verbose_name='Автор'),
        ),
    ]
