# Generated by Django 4.1.2 on 2022-10-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0012_alter_checkstatus__check_alter_checkstatus_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkstatus',
            name='_check',
        ),
        migrations.AddField(
            model_name='checkstatus',
            name='check_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projecta.check'),
            preserve_default=False,
        ),
    ]
