# Generated by Django 4.1.2 on 2022-10-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0015_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('Director', 'Руководитель'), ('Engineer', 'Инженер'), ('Accountant', 'Бухгалтер'), ('Plumber', 'Слесарь')], default='Plumber', max_length=20, verbose_name='Позиция'),
        ),
    ]
