# Generated by Django 4.1.2 on 2022-10-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0016_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='projecta.executor', verbose_name='Испонитель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projecta.executor', verbose_name='Испонитель'),
            preserve_default=False,
        ),
    ]
