# Generated by Django 4.1.2 on 2022-10-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0017_act_executor_ticket_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='executor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='projecta.executor', verbose_name='Испонитель'),
            preserve_default=False,
        ),
    ]
