# Generated by Django 4.1.2 on 2022-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0018_equipment_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='check_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='act',
            name='check_status',
            field=models.CharField(choices=[('Не выставлен', 'Не выставлен'), ('Выставлен', 'Выставлен'), ('Не оплачен', 'Не оплачен'), ('Оплачен', 'Оплачен')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
