# Generated by Django 4.1.2 on 2022-10-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0019_act_check_number_act_check_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='check_status',
            field=models.CharField(choices=[('Не выставлен', 'Не выставлен'), ('Выставлен', 'Выставлен'), ('Не оплачен', 'Не оплачен'), ('Оплачен', 'Оплачен')], default='Не выставлен', max_length=255),
        ),
    ]
