# Generated by Django 4.1.2 on 2022-10-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0020_alter_act_check_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='act',
            old_name='status',
            new_name='act_status',
        ),
    ]
