# Generated by Django 4.1.2 on 2022-10-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0021_rename_status_act_act_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkstatus',
            name='_check',
        ),
        migrations.RenameField(
            model_name='actstatus',
            old_name='status',
            new_name='act_status',
        ),
        migrations.AddField(
            model_name='actstatus',
            name='check_status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='CheckStatus',
        ),
    ]
