# Generated by Django 4.1.2 on 2022-11-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0022_remove_checkstatus__check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_status',
            field=models.CharField(choices=[('Б/С', 'Б/С'), ('У клиента', 'У клиента'), ('Подписан', 'Подписан'), ('ЭДО', 'ЭДО')], default='Б/С', max_length=255, verbose_name='Статус акта'),
        ),
        migrations.AlterField(
            model_name='act',
            name='check_number',
            field=models.CharField(max_length=255, verbose_name='Номер счёта'),
        ),
        migrations.AlterField(
            model_name='act',
            name='check_status',
            field=models.CharField(choices=[('Не выставлен', 'Не выставлен'), ('Выставлен', 'Выставлен'), ('Не оплачен', 'Не оплачен'), ('Оплачен', 'Оплачен')], default='Не выставлен', max_length=255, verbose_name='Статус счёта'),
        ),
    ]
