# Generated by Django 4.1.2 on 2022-11-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0024_alter_act_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='date_reg_certificate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата регистрации'),
        ),
    ]
