# Generated by Django 4.1.2 on 2022-11-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0028_ticket_comment_alter_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
