# Generated by Django 4.1.2 on 2022-11-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0028_alter_client_is_active_alter_client_phone_and_more'),
        ('projecta', '0029_alter_ticket_comment'),
    ]

    operations = [
    ]
