# Generated by Django 4.1.2 on 2022-11-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0030_merge_20221124_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='date_from',
            field=models.DateField(default='1970-01-01', verbose_name='Начало эксплуатации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='date_to',
            field=models.DateField(default='1970-01-01', verbose_name='Конец эксплуатации'),
            preserve_default=False,
        ),
    ]
