# Generated by Django 4.1.2 on 2022-11-24 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0031_equipment_date_from_equipment_date_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.TextField(verbose_name='Лицензия')),
                ('date_reg', models.DateField(verbose_name='Дата регистрации')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='projecta.executor', verbose_name='Компания')),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='license',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='projecta.license', verbose_name='Лицензия'),
            preserve_default=False,
        ),
    ]
