# Generated by Django 4.1.2 on 2022-11-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0032_license_agreement_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executor',
            name='num_reg_certificate',
        ),
    ]
