# Generated by Django 4.1.2 on 2022-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0034_remove_agreement_license_license_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='agreement',
        ),
        migrations.AddField(
            model_name='agreement',
            name='licence',
            field=models.IntegerField(default=1, verbose_name='Лицензия'),
            preserve_default=False,
        ),
    ]
