# Generated by Django 4.1.2 on 2022-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0035_remove_license_agreement_agreement_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='licence',
            field=models.TextField(verbose_name='Лицензия'),
        ),
    ]
