# Generated by Django 4.1.2 on 2022-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0037_alter_license_options_alter_license_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='licence',
            field=models.TextField(blank=True, null=True, verbose_name='Лицензия'),
        ),
    ]
