# Generated by Django 4.1.2 on 2022-11-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0039_alter_ticket_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agreement',
            old_name='licence',
            new_name='license',
        ),
    ]
