# Generated by Django 4.1.3 on 2022-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0040_rename_licence_agreement_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_number',
            field=models.CharField(error_messages={'unique': 'Required error'}, max_length=255, verbose_name='Номер договора'),
        ),
    ]
