# Generated by Django 4.1.3 on 2022-12-14 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0044_equipmentphoto_author_equipmentphoto_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='class_danger',
            field=models.CharField(default='3 класс', max_length=255, verbose_name='Класс опасности'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='execution_date',
            field=models.DateField(default=datetime.date(2022, 12, 31), verbose_name='Дата выполнения'),
        ),
    ]
