# Generated by Django 4.1.3 on 2022-12-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0045_license_class_danger_ticket_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='class_danger',
            field=models.CharField(choices=[('Нет класса', 'Нет класса'), ('1 класс', '1 класс'), ('2 класс', '2 класс'), ('3 класс', '3 класс'), ('4 класс', '4 класс')], default='Нет', max_length=255, verbose_name='Класс опасности'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='execution_date',
            field=models.DateField(verbose_name='Дата выполнения'),
        ),
    ]
