# Generated by Django 4.1.4 on 2022-12-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0046_alter_license_class_danger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='org_form',
            field=models.CharField(default='Не определено', max_length=15, verbose_name='Форма организации'),
        ),
    ]
