# Generated by Django 4.1.4 on 2022-12-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0047_client_org_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='org_form',
            field=models.CharField(choices=[('ООО', 'ООО'), ('ИП', 'ИП'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО')], default='Не определено', max_length=15, verbose_name='Форма организации'),
        ),
    ]
