# Generated by Django 4.1.3 on 2022-12-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0048_alter_client_org_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='executor',
            name='org_form',
            field=models.CharField(choices=[('Не определено', 'Не определено'), ('ООО', 'ООО'), ('ИП', 'ИП'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО')], default='Не определено', max_length=15, verbose_name='Форма организации'),
        ),
        migrations.AlterField(
            model_name='client',
            name='org_form',
            field=models.CharField(choices=[('Не определено', 'Не определено'), ('ООО', 'ООО'), ('ИП', 'ИП'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО')], default='Не определено', max_length=15, verbose_name='Форма организации'),
        ),
    ]
