# Generated by Django 4.1.3 on 2023-01-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0049_executor_org_form_alter_client_org_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name', '-updated', '-created'), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиент'},
        ),
        migrations.AlterField(
            model_name='client',
            name='org_form',
            field=models.CharField(choices=[('Не определено', 'Не определено'), ('ООО', 'ООО'), ('ИП', 'ИП'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО'), ('АО', 'АО'), ('ПАО', 'ПАО'), ('НАО', 'НАО'), ('НКО', 'НКО'), ('гр.', 'гр.')], default='Не определено', max_length=15, verbose_name='Форма организации'),
        ),
    ]
