# Generated by Django 4.1.4 on 2023-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0050_alter_client_options_alter_client_org_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='org_form',
            field=models.CharField(choices=[('Не определено', 'Не определено'), ('ООО', 'ООО'), ('ИП', 'ИП'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО'), ('АО', 'АО'), ('ПАО', 'ПАО'), ('НАО', 'НАО'), ('НКО', 'НКО'), ('гр.', 'гр.'), ('МБОУ', 'МБОУ'), ('ТСН', 'ТСН')], default='Не определено', max_length=15, verbose_name='Форма организации'),
        ),
        migrations.AlterField(
            model_name='executor',
            name='org_form',
            field=models.CharField(choices=[('Не определено', 'Не определено'), ('ООО', 'ООО'), ('ИП', 'ИП'), ('ОАО', 'ОАО'), ('ЗАО', 'ЗАО'), ('АО', 'АО'), ('ПАО', 'ПАО'), ('НАО', 'НАО'), ('НКО', 'НКО'), ('гр.', 'гр.'), ('МБОУ', 'МБОУ'), ('ТСН', 'ТСН')], default='Не определено', max_length=15, verbose_name='Форма организации'),
        ),
    ]
