# Generated by Django 4.1.4 on 2023-01-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0051_alter_client_org_form_alter_executor_org_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='actstatus',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projecta.executor'),
        ),
        migrations.AddField(
            model_name='agreementstatus',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projecta.executor'),
        ),
        migrations.AddField(
            model_name='clientstatus',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projecta.executor'),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projecta.executor'),
        ),
    ]
