# Generated by Django 4.1.4 on 2023-01-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0053_alter_actstatus_executor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actstatus',
            name='executor',
            field=models.IntegerField(default=0, verbose_name='Компания исполнитель'),
        ),
        migrations.AlterField(
            model_name='agreementstatus',
            name='executor',
            field=models.IntegerField(default=0, verbose_name='Компания исполнитель'),
        ),
        migrations.AlterField(
            model_name='clientstatus',
            name='executor',
            field=models.IntegerField(default=0, verbose_name='Компания исполнитель'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='executor',
            field=models.IntegerField(default=0, verbose_name='Компания исполнитель'),
        ),
    ]
