# Generated by Django 4.1.4 on 2023-01-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0055_test_lnsurancepolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lnsurancepolicy',
            options={'verbose_name': 'Страховой полис', 'verbose_name_plural': 'Страховые полисы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelTable(
            name='lnsurancepolicy',
            table='lnsurance_policy',
        ),
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
    ]
