# Generated by Django 4.1.4 on 2023-01-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0056_alter_lnsurancepolicy_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LnsurancePolicy',
            new_name='InsurancePolicy',
        ),
    ]
