# Generated by Django 4.1.4 on 2023-01-31 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0057_rename_lnsurancepolicy_insurancepolicy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='insurancepolicy',
            table='insurance_policy',
        ),
    ]
