# Generated by Django 4.1.4 on 2023-01-31 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0058_alter_insurancepolicy_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='agreement_id',
            new_name='agreement',
        ),
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='executor_id',
            new_name='executor',
        ),
    ]
