# Generated by Django 4.1.4 on 2023-01-31 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0059_rename_agreement_id_insurancepolicy_agreement_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
