# Generated by Django 4.1.4 on 2023-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0060_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен?'),
        ),
    ]
