# Generated by Django 4.1.4 on 2023-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0061_agreement_is_delete_client_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementstatus',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AddField(
            model_name='clientstatus',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
    ]
