# Generated by Django 4.1.4 on 2023-02-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0064_alter_agreement_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementstatus',
            name='responsible',
            field=models.IntegerField(null=True, verbose_name='Ответственный'),
        ),
    ]
