# Generated by Django 3.2.16 on 2023-02-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0065_alter_agreementstatus_responsible'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('created',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_sys_user',
            field=models.BooleanField(default=True, verbose_name='Системный ли пользователь?'),
        ),
    ]
