# Generated by Django 3.2.16 on 2023-02-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecta', '0066_auto_20230217_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_sys_user',
            field=models.BooleanField(default=False, verbose_name='Системный ли пользователь?'),
        ),
    ]
